### ISSUE TITLE
Benchmark Crash on 0.18 Update

### ISSUE THREAD

**Issue by christophwille** [christophwille/csharp-opa-wasm#8]
```
WorkloadActual  51: 256 op, 1953480400.00 ns, 7.6308 ms/op
WorkloadActual  52: 256 op, 1710074000.00 ns, 6.6800 ms/op
WorkloadActual  53: 256 op, 1751066000.00 ns, 6.8401 ms/op
WorkloadActual  54: 256 op, 1754423700.00 ns, 6.8532 ms/op
WorkloadActual  55: 256 op, 1776180900.00 ns, 6.9382 ms/op
WorkloadActual  56: 256 op, 2003734500.00 ns, 7.8271 ms/op
WorkloadActual  57: 256 op, 2259331700.00 ns, 8.8255 ms/op
thread '<unnamed>' panicked at 'allocate_for_function: "The paging file is too small for this operation to complete. (os error 1455)"', crates\wasmtime\src\trampoline\func.rs:194:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: Rust panics must be rethrown
ExitCode != 0
// Benchmark Process 4752 has exited with code -1073740791
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!


// ***** BenchmarkRunner: Finish  *****
```

The benchmark code is only minimally changed (instead of LoadModule every time, it is done once in ctor)

https://github.com/christophwille/csharp-opa-wasm/blob/master/spikes/BenchmarkOpaWasm/Program.cs#L16

The store is only thinly wrapped (to later be able to something smart, didn't spend time on API design)

https://github.com/christophwille/csharp-opa-wasm/blob/master/src/Opa.Wasm/OpaPolicyStore.cs#L17

and basically all of that is passed to OpaPolicy in the ctor:

https://github.com/christophwille/csharp-opa-wasm/blob/master/src/Opa.Wasm/OpaPolicy.cs#L20

@peterhuene any ideas what I did wrong this time? (none of the wasm's changed since last time)

**Comment by peterhuene** [comment]
There appears to be a memory leak (or native memory pressure on the GC) somewhere; I do see you're disposing of things properly for the benchmark method, so that isn't the problem.  I'll see if I can reproduce it with a simple repro and I'll investigate.

**Comment by peterhuene** [comment]
I've reproduced the issue and will have a fix available shortly (I'll release a 0.18.1 package with it).  The problem is that the host isn't using a *separate store* for allocating the things it defines, which means things like the Wasm memory being defined aren't being deallocated when the host is disposed; instead they are being deallocated with the store.

**Comment by peterhuene** [comment]
I've opened https://github.com/bytecodealliance/wasmtime-dotnet/pull/24 for the fix (also added a benchmark test that reproduced the issue).

**Comment by peterhuene** [comment]
@christophwille I've pushed up `0.18.1-preview1` of the package (in retrospect I should probably have called that `preview2` and kept the version number to match the underlying Wasmtime version, oh well).

Note that this had a breaking API change in it, something I don't like doing for a patch, but we needed to reintroduce the `Engine` type back in to fix this for you.

Thus, you'll need to update your code once more:

```
using var engine = new Engine();
using var store = new Store(engine);
...

using var host = new Host(engine);
```

Note that both `Store` and `Host` take the engine as an argument now.

The .NET API is still in flux, obviously.  Some changes in Wasmtime a few weeks ago will allow us to eliminate the `Store` type entirely and turn the `LoadModuleXXX` methods into constructors on `Module`.  There's one remaining change in Wasmtime  that is needed for that to happen, so that's not happening just yet, but keep in mind more breaking changes will happen as we can simplify the API.

Let me know if you run into any problems.  Thanks!

**Comment by christophwille** [comment]
Thanks for taking the time looking into this! 

I have updated my codebase & the benchmark runs now smoothly, timings are here with comparison to old (pre-0.15)

https://github.com/christophwille/csharp-opa-wasm/commit/d3147291ed3c75a718f16350408379e4d0090819#diff-e667984d95f67b42f7d1a310bd2d9bbdL10

Given your comment on `new Module()` futures I have folded the Engine in the class OpaModule (basically mapping store & module 1:1 to keep things simple):

https://github.com/christophwille/csharp-opa-wasm/commit/d3147291ed3c75a718f16350408379e4d0090819#diff-36480c18cc3dbb23bdb1b5746df2c854R6
